networks:
  go-user:
    driver: bridge

services:
  go-user-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: go-user-app-container
    depends_on:
      - go-user-db-postgres
    environment:
      APP_ENVIRONMENT: prod
      HTTP_HOST: 0.0.0.0
      GRPC_HOST: 0.0.0.0
      POSTGRES_HOST: go-user-db-postgres-container
      POSTGRES_PORT: 5432
    image: go-user-app
    networks:
      - go-user
    ports:
      - "10000:10000"
      - "11000:11000"
  go-user-db-postgres:
    container_name: go-user-db-postgres-container
    environment:
      POSTGRES_DB: playground
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    image: postgres:16
    networks:
      - go-user
    ports:
      - "5000:5432"
