// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: pkg/gouser/grpc/pb/auth.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthEmpty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AuthEmpty) Reset() {
	*x = AuthEmpty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gouser_grpc_pb_auth_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthEmpty) ProtoMessage() {}

func (x *AuthEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gouser_grpc_pb_auth_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthEmpty.ProtoReflect.Descriptor instead.
func (*AuthEmpty) Descriptor() ([]byte, []int) {
	return file_pkg_gouser_grpc_pb_auth_proto_rawDescGZIP(), []int{0}
}

type ReqLoginUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *ReqLoginUser) Reset() {
	*x = ReqLoginUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gouser_grpc_pb_auth_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqLoginUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLoginUser) ProtoMessage() {}

func (x *ReqLoginUser) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gouser_grpc_pb_auth_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLoginUser.ProtoReflect.Descriptor instead.
func (*ReqLoginUser) Descriptor() ([]byte, []int) {
	return file_pkg_gouser_grpc_pb_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ReqLoginUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ReqLoginUser) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ResLoginUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserJwt string `protobuf:"bytes,1,opt,name=user_jwt,json=userJwt,proto3" json:"user_jwt,omitempty"`
}

func (x *ResLoginUser) Reset() {
	*x = ResLoginUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gouser_grpc_pb_auth_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResLoginUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResLoginUser) ProtoMessage() {}

func (x *ResLoginUser) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gouser_grpc_pb_auth_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResLoginUser.ProtoReflect.Descriptor instead.
func (*ResLoginUser) Descriptor() ([]byte, []int) {
	return file_pkg_gouser_grpc_pb_auth_proto_rawDescGZIP(), []int{2}
}

func (x *ResLoginUser) GetUserJwt() string {
	if x != nil {
		return x.UserJwt
	}
	return ""
}

type ReqRegisterUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *ReqRegisterUser) Reset() {
	*x = ReqRegisterUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gouser_grpc_pb_auth_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqRegisterUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqRegisterUser) ProtoMessage() {}

func (x *ReqRegisterUser) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gouser_grpc_pb_auth_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqRegisterUser.ProtoReflect.Descriptor instead.
func (*ReqRegisterUser) Descriptor() ([]byte, []int) {
	return file_pkg_gouser_grpc_pb_auth_proto_rawDescGZIP(), []int{3}
}

func (x *ReqRegisterUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ReqRegisterUser) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ResRegisterUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId int64 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *ResRegisterUser) Reset() {
	*x = ResRegisterUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gouser_grpc_pb_auth_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResRegisterUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResRegisterUser) ProtoMessage() {}

func (x *ResRegisterUser) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gouser_grpc_pb_auth_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResRegisterUser.ProtoReflect.Descriptor instead.
func (*ResRegisterUser) Descriptor() ([]byte, []int) {
	return file_pkg_gouser_grpc_pb_auth_proto_rawDescGZIP(), []int{4}
}

func (x *ResRegisterUser) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

var File_pkg_gouser_grpc_pb_auth_proto protoreflect.FileDescriptor

var file_pkg_gouser_grpc_pb_auth_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x6f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x70, 0x62, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x02, 0x70, 0x62, 0x22, 0x0b, 0x0a, 0x09, 0x41, 0x75, 0x74, 0x68, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x46, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72,
	0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x29, 0x0a, 0x0c, 0x52, 0x65, 0x73, 0x4c,
	0x6f, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x6a, 0x77, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x4a, 0x77, 0x74, 0x22, 0x49, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x2a,
	0x0a, 0x0f, 0x52, 0x65, 0x73, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x32, 0x75, 0x0a, 0x04, 0x41, 0x75,
	0x74, 0x68, 0x12, 0x31, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x65, 0x72, 0x12,
	0x10, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x55, 0x73, 0x65,
	0x72, 0x1a, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x55,
	0x73, 0x65, 0x72, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0c, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x55, 0x73, 0x65, 0x72, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x71, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x1a, 0x13, 0x2e, 0x70, 0x62, 0x2e,
	0x52, 0x65, 0x73, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72, 0x22,
	0x00, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x48, 0x69, 0x64, 0x61, 0x79, 0x61, 0x74, 0x68, 0x61, 0x6d, 0x69, 0x72, 0x2f, 0x67, 0x6f, 0x75,
	0x73, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x6f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_gouser_grpc_pb_auth_proto_rawDescOnce sync.Once
	file_pkg_gouser_grpc_pb_auth_proto_rawDescData = file_pkg_gouser_grpc_pb_auth_proto_rawDesc
)

func file_pkg_gouser_grpc_pb_auth_proto_rawDescGZIP() []byte {
	file_pkg_gouser_grpc_pb_auth_proto_rawDescOnce.Do(func() {
		file_pkg_gouser_grpc_pb_auth_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_gouser_grpc_pb_auth_proto_rawDescData)
	})
	return file_pkg_gouser_grpc_pb_auth_proto_rawDescData
}

var file_pkg_gouser_grpc_pb_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_gouser_grpc_pb_auth_proto_goTypes = []interface{}{
	(*AuthEmpty)(nil),       // 0: pb.AuthEmpty
	(*ReqLoginUser)(nil),    // 1: pb.ReqLoginUser
	(*ResLoginUser)(nil),    // 2: pb.ResLoginUser
	(*ReqRegisterUser)(nil), // 3: pb.ReqRegisterUser
	(*ResRegisterUser)(nil), // 4: pb.ResRegisterUser
}
var file_pkg_gouser_grpc_pb_auth_proto_depIdxs = []int32{
	1, // 0: pb.Auth.LoginUser:input_type -> pb.ReqLoginUser
	3, // 1: pb.Auth.RegisterUser:input_type -> pb.ReqRegisterUser
	2, // 2: pb.Auth.LoginUser:output_type -> pb.ResLoginUser
	4, // 3: pb.Auth.RegisterUser:output_type -> pb.ResRegisterUser
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_gouser_grpc_pb_auth_proto_init() }
func file_pkg_gouser_grpc_pb_auth_proto_init() {
	if File_pkg_gouser_grpc_pb_auth_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_gouser_grpc_pb_auth_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthEmpty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gouser_grpc_pb_auth_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqLoginUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gouser_grpc_pb_auth_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResLoginUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gouser_grpc_pb_auth_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqRegisterUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gouser_grpc_pb_auth_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResRegisterUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_gouser_grpc_pb_auth_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_gouser_grpc_pb_auth_proto_goTypes,
		DependencyIndexes: file_pkg_gouser_grpc_pb_auth_proto_depIdxs,
		MessageInfos:      file_pkg_gouser_grpc_pb_auth_proto_msgTypes,
	}.Build()
	File_pkg_gouser_grpc_pb_auth_proto = out.File
	file_pkg_gouser_grpc_pb_auth_proto_rawDesc = nil
	file_pkg_gouser_grpc_pb_auth_proto_goTypes = nil
	file_pkg_gouser_grpc_pb_auth_proto_depIdxs = nil
}
