// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: pkg/gousergrpc/profile.proto

package gousergrpc

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProfileEmpty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProfileEmpty) Reset() {
	*x = ProfileEmpty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gousergrpc_profile_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProfileEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfileEmpty) ProtoMessage() {}

func (x *ProfileEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gousergrpc_profile_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProfileEmpty.ProtoReflect.Descriptor instead.
func (*ProfileEmpty) Descriptor() ([]byte, []int) {
	return file_pkg_gousergrpc_profile_proto_rawDescGZIP(), []int{0}
}

type ReqGetProfileByUsername struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *ReqGetProfileByUsername) Reset() {
	*x = ReqGetProfileByUsername{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gousergrpc_profile_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqGetProfileByUsername) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqGetProfileByUsername) ProtoMessage() {}

func (x *ReqGetProfileByUsername) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gousergrpc_profile_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqGetProfileByUsername.ProtoReflect.Descriptor instead.
func (*ReqGetProfileByUsername) Descriptor() ([]byte, []int) {
	return file_pkg_gousergrpc_profile_proto_rawDescGZIP(), []int{1}
}

func (x *ReqGetProfileByUsername) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type ResGetProfileByUsername struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username  string               `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	CreatedAt *timestamp.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt *timestamp.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *ResGetProfileByUsername) Reset() {
	*x = ResGetProfileByUsername{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gousergrpc_profile_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResGetProfileByUsername) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResGetProfileByUsername) ProtoMessage() {}

func (x *ResGetProfileByUsername) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gousergrpc_profile_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResGetProfileByUsername.ProtoReflect.Descriptor instead.
func (*ResGetProfileByUsername) Descriptor() ([]byte, []int) {
	return file_pkg_gousergrpc_profile_proto_rawDescGZIP(), []int{2}
}

func (x *ResGetProfileByUsername) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResGetProfileByUsername) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ResGetProfileByUsername) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ResGetProfileByUsername) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ReqUpdateProfileByUserID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserJwt  string `protobuf:"bytes,1,opt,name=user_jwt,json=userJwt,proto3" json:"user_jwt,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *ReqUpdateProfileByUserID) Reset() {
	*x = ReqUpdateProfileByUserID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_gousergrpc_profile_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqUpdateProfileByUserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqUpdateProfileByUserID) ProtoMessage() {}

func (x *ReqUpdateProfileByUserID) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_gousergrpc_profile_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqUpdateProfileByUserID.ProtoReflect.Descriptor instead.
func (*ReqUpdateProfileByUserID) Descriptor() ([]byte, []int) {
	return file_pkg_gousergrpc_profile_proto_rawDescGZIP(), []int{3}
}

func (x *ReqUpdateProfileByUserID) GetUserJwt() string {
	if x != nil {
		return x.UserJwt
	}
	return ""
}

func (x *ReqUpdateProfileByUserID) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_pkg_gousergrpc_profile_proto protoreflect.FileDescriptor

var file_pkg_gousergrpc_profile_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x6f, 0x75, 0x73, 0x65, 0x72, 0x67, 0x72, 0x70, 0x63,
	0x2f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x67, 0x6f, 0x75, 0x73, 0x65, 0x72, 0x67, 0x72, 0x70, 0x63, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0e, 0x0a, 0x0c, 0x50,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x35, 0x0a, 0x17, 0x52,
	0x65, 0x71, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x42, 0x79, 0x55, 0x73,
	0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0xbb, 0x01, 0x0a, 0x17, 0x52, 0x65, 0x73, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x22, 0x51, 0x0a, 0x18, 0x52, 0x65, 0x71, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x19, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x6a, 0x77, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x4a, 0x77, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77,
	0x6f, 0x72, 0x64, 0x32, 0xc8, 0x01, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12,
	0x62, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x42, 0x79, 0x55,
	0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x23, 0x2e, 0x67, 0x6f, 0x75, 0x73, 0x65, 0x72,
	0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x71, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x23, 0x2e, 0x67,
	0x6f, 0x75, 0x73, 0x65, 0x72, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x47, 0x65, 0x74,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d,
	0x65, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x24, 0x2e, 0x67,
	0x6f, 0x75, 0x73, 0x65, 0x72, 0x67, 0x72, 0x70, 0x63, 0x2e, 0x52, 0x65, 0x71, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x44, 0x1a, 0x18, 0x2e, 0x67, 0x6f, 0x75, 0x73, 0x65, 0x72, 0x67, 0x72, 0x70, 0x63, 0x2e,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x2f,
	0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x48, 0x69, 0x64,
	0x61, 0x79, 0x61, 0x74, 0x68, 0x61, 0x6d, 0x69, 0x72, 0x2f, 0x67, 0x6f, 0x75, 0x73, 0x65, 0x72,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x6f, 0x75, 0x73, 0x65, 0x72, 0x67, 0x72, 0x70, 0x63, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_gousergrpc_profile_proto_rawDescOnce sync.Once
	file_pkg_gousergrpc_profile_proto_rawDescData = file_pkg_gousergrpc_profile_proto_rawDesc
)

func file_pkg_gousergrpc_profile_proto_rawDescGZIP() []byte {
	file_pkg_gousergrpc_profile_proto_rawDescOnce.Do(func() {
		file_pkg_gousergrpc_profile_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_gousergrpc_profile_proto_rawDescData)
	})
	return file_pkg_gousergrpc_profile_proto_rawDescData
}

var file_pkg_gousergrpc_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_gousergrpc_profile_proto_goTypes = []interface{}{
	(*ProfileEmpty)(nil),             // 0: gousergrpc.ProfileEmpty
	(*ReqGetProfileByUsername)(nil),  // 1: gousergrpc.ReqGetProfileByUsername
	(*ResGetProfileByUsername)(nil),  // 2: gousergrpc.ResGetProfileByUsername
	(*ReqUpdateProfileByUserID)(nil), // 3: gousergrpc.ReqUpdateProfileByUserID
	(*timestamp.Timestamp)(nil),      // 4: google.protobuf.Timestamp
}
var file_pkg_gousergrpc_profile_proto_depIdxs = []int32{
	4, // 0: gousergrpc.ResGetProfileByUsername.created_at:type_name -> google.protobuf.Timestamp
	4, // 1: gousergrpc.ResGetProfileByUsername.updated_at:type_name -> google.protobuf.Timestamp
	1, // 2: gousergrpc.Profile.GetProfileByUsername:input_type -> gousergrpc.ReqGetProfileByUsername
	3, // 3: gousergrpc.Profile.UpdateProfileByUserID:input_type -> gousergrpc.ReqUpdateProfileByUserID
	2, // 4: gousergrpc.Profile.GetProfileByUsername:output_type -> gousergrpc.ResGetProfileByUsername
	0, // 5: gousergrpc.Profile.UpdateProfileByUserID:output_type -> gousergrpc.ProfileEmpty
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_gousergrpc_profile_proto_init() }
func file_pkg_gousergrpc_profile_proto_init() {
	if File_pkg_gousergrpc_profile_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_gousergrpc_profile_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProfileEmpty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gousergrpc_profile_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqGetProfileByUsername); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gousergrpc_profile_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResGetProfileByUsername); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_gousergrpc_profile_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqUpdateProfileByUserID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_gousergrpc_profile_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_gousergrpc_profile_proto_goTypes,
		DependencyIndexes: file_pkg_gousergrpc_profile_proto_depIdxs,
		MessageInfos:      file_pkg_gousergrpc_profile_proto_msgTypes,
	}.Build()
	File_pkg_gousergrpc_profile_proto = out.File
	file_pkg_gousergrpc_profile_proto_rawDesc = nil
	file_pkg_gousergrpc_profile_proto_goTypes = nil
	file_pkg_gousergrpc_profile_proto_depIdxs = nil
}
