app:
  name: 'go-user'
  version: '1.0.0'
  environment: 'dev' # 'prod', 'dev'

http:
  host: "localhost"
  port: 8080

logger:
  log_level: 'debug' # 'panic', 'fatal', 'error', 'warn', 'warning', 'info', 'debug', 'trace'

postgres:
  pool_max: 2
  username: "user"
  password: "password"
  host: "localhost"
  port: 5432
  db_name: "playground"
