app:
  name: "go-user"
  version: "1.0.0"
  environment: "dev" # 'prod', 'dev'

http:
  host: "localhost"
  port: 10000

grpc:
  host: "localhost"
  port: 11000

logger:
  log_level: "debug" # 'panic', 'fatal', 'error', 'warn', 'warning', 'info', 'debug', 'trace'

postgres:
  pool_max: 2
  username: "user"
  password: "password"
  host: "localhost"
  port: 5000
  db_name: "playground"

jwt:
  expire_hour: 36
  signed_key: "5f4a252a-539b-47f6-2224-d4c2edd71ca4"
