app:
  name: 'go-user'
  version: '1.0.0'
  environment: 'dev'

http:
  port: 8080

logger:
  log_level: 'debug'

postgres:
  pool_max: 2
  username: "user"
  password: "password"
  host: "localhost"
  port: 5432
  db_name: "playground"
